spring:
  redis:
    password: x
    sentinel:
      master: master7922
      nodes: localhost:17922,localhost:17922
  cache:
    type: CAFFEINE  # org.springframework.boot.autoconfigure.cache.CacheType
    cache-names: cache1,cache2
    redis:
      time-to-live: 120m
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=1800s

