spring:
  redis:
    password: x
    sentinel:
      master: master7922
      nodes: localhost:17922,localhost:17922
  cache:  # org.springframework.boot.autoconfigure.cache.CacheProperties
    type: CAFFEINE  # org.springframework.boot.autoconfigure.cache.CacheType
    cache-names: cache1,cache2
    redis:  # org.springframework.boot.autoconfigure.cache.CacheProperties.Redis
      time-to-live: 60m # 会被 com.ozz.cache.config.MyRedisCacheConfig 覆盖
    caffeine: # com.github.benmanes.caffeine.cache.CaffeineSpec
      spec: maximumSize=10000,expireAfterWrite=600s

